server:
  port: 8000
spring:
  application:
    name: eureka-server
# disable eureka-server register self as  client
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
